<?php
$a=10;
$b=5;
$tambah=$a+$b;
$kurang=$a-$b;
$kali=$a*$b;
$bagi=$a/$b;
$mod=$a%$b;
$pangkat=$a**$b;
echo"A: {$a}, B: {$b}<br>";
echo"Hasil Tambah A+B: {$tambah}<br>";
echo"Hasil Kurang A-B: {$kurang}<br>";
echo"Hasil Kali A*B: {$kali}<br>";
echo"Hasil Bagi A/B: {$bagi}<br>";
echo"Sisa Bagi A%B: {$mod}<br>";
echo"Hasil Pangkat A^B: {$pangkat}<br>";
echo "----------------------------------<br>";
$hasilSama=$a==$b;
$hasilTakSama=$a!=$b;
$hasilKurDari=$a<$b;
$hasilLeDari=$a>$b;
$hasilKurDarSama=$a<=$b;
$hasilLeDarSama=$a>=$b;
echo"Hasil Sama Dengan A==B: {$hasilSama}<br>";
echo"Hasil Tak Sama Dengan A!=B: {$hasilTakSama}<br>";
echo"Hasil Kurang Dari A<B: {$hasilKurDari}<br>";
echo"Hasil Lebih Dari A>B: {$hasilLeDari}<br>";
echo "Hasil Kurang Dari Sama Dengan A<=B: {$hasilKurDarSama}<br>";
echo "Hasil Lebih Dari Sama Dengan A>=B: {$hasilLeDarSama}<br>";
echo "----------------------------------<br>";
$hasilAnd=$a&&$b;
$hasilOr=$a||$b;
$hasilNotA=!$a;
$hasilNotB=!$b;
echo"Hasil And A&&B: {$hasilAnd}<br>";
echo "Hasil Or A||B: {$hasilOr}<br>";
echo "Hasil Not A: {$hasilNotA}<br>";
echo "Hasil Not B: {$hasilNotB}<br>";
echo "----------------------------------<br>";
echo $a+=$b; echo"<br>";
echo $a-=$b; echo"<br>";
echo $a*=$b; echo"<br>";
echo $a/=$b; echo"<br>";
echo $a%=$b; echo"<br>";
echo "----------------------------------<br>";
$hasilIdentik=$a===$b;
$hasilTakIdentik=$a!==$b;
echo"Hasil Identik A===B: {$hasilIdentik}<br>";
echo "Hasil Tak Identik A!==B: {$hasilTakIdentik}<br>";
echo "----------------------------------<br>";
?>